# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - name: test
      run: fastlane scan
